### ISSUE TITLE
配置HTTPS和SSL通信后报错

### ISSUE THREAD

**Issue by WandQ** [secretflow/scql#111]
我在本地利用docker模拟多台机器后部署了scql项目，并成功跑通了样例demo
我来我尝试使用https进行通信，将https的选项和ssl的选项都打开后，用本地ca自签生成了三份不同的server.key和server.crt文件分别给SCDB和ALICE和BOB。发送查询任务时出现了以下错误
![image](https://github.com/secretflow/scql/assets/56994734/2f891ace-2445-4af4-a686-45f4c1e63fca)
附配置文件：
config.yml：
```
scdb_host: https://localhost:8080
port: 8080
protocol: https
tls:
  cert_file: /data/ssl_certs/server.crt
  key_file: /data/ssl_certs/server.key
query_result_callback_timeout: 3m
session_expire_time: 3m
session_expire_check_time: 100ms
log_level: debug
storage:
  type: mysql
  conn_str: "root:testpass@tcp(172.23.13.246:3306)/scdb?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
grm:
  grm_mode: toygrm
  toy_grm_conf: /home/admin/configs/toy_grm.json
engine:
  timeout: 120s
  protocol: https
  content_type: application/json
  spu:
    protocol: SEMI2K
    field: FM64
    sigmoid_mode: SIGMOID_REAL
``` 

gflags.conf :
```
--listen_port=8080
--datasource_router=embed
--enable_scdb_authorization=true
--engine_credential=__ALICE_CREDENTIAL__
--server_enable_ssl=true
--server_ssl_certificate=/data/ssl_certs/server.crt
--server_ssl_private_key=/data/ssl_certs/server.key
--scdb_enable_ssl_as_client=true
--peer_engine_enable_ssl_as_client=true
--embed_router_conf={"datasources":[{"id":"ds001","name":"mysql db","kind":"MYSQL","connection_str":"db=alice;user=root;password=testpass;host=172.23.13.246;port=3307;auto-re:connect=true"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
```
