### ISSUE TITLE
Create database, user and tables 问题

### ISSUE THREAD

**Issue by Repo-Zhuang** [secretflow/scql#15]
```
(base) PS D:\scql> docker exec -it scql-dev-user  bash
(base) [root@a6f931ea272b dev]# ./scdbclient prompt --host=http://localhost:8080 --usersConfFileName=examples/docker-compose/client/users.json --sync
> switch root
root> show databases;
[submit and get]err: Post "http://localhost:8080/public/submit_and_get": dial tcp 127.0.0.1:8080: connect: connection refused
```
请问这个问题怎么解决

**Comment by tongke6** [comment]
@Repo-Zhuang 你好，这是 docker 网络隔离导致的。在 docker 里面无法通过 localhost 访问 docker-compose 暴露的 8080 端口。如果你有需求在 docker 里运行 scdbclient，可以尝试将 localhost 改成宿主机的 ip 地址。

**Comment by Repo-Zhuang** [comment]
我将 localhost 改成本机主机的 ip 地址后显示connect: no route to host的错误
```
(base) [root@a6f931ea272b dev]# ./scdbclient prompt --host=http://172.17.76.1:8080 --usersConfFileName=examples/docker-compose/client/users.json --sync
> switch root
root> show database;
[submit and get]err: Post "http://172.17.76.1:8080/public/submit_and_get": dial tcp 172.17.76.1:8080: connect: no route to host
```

**Comment by tyrone-yu** [comment]
> 我将 localhost 改成本机主机的 ip 地址后显示connect: no route to host的错误
> 
> ```
> (base) [root@a6f931ea272b dev]# ./scdbclient prompt --host=http://172.17.76.1:8080 --usersConfFileName=examples/docker-compose/client/users.json --sync
> > switch root
> root> show database;
> [submit and get]err: Post "http://172.17.76.1:8080/public/submit_and_get": dial tcp 172.17.76.1:8080: connect: no route to host
> ```

请问 docker 容器是在 windows 系统上运行么？如果是在 windows 系统的话，可能需要通过访问 http://host.docker.internal/ 来访问宿主机上的端口。所以可以将 172.17.76.1 替换成 host.docker.internal 尝试一下

**Comment by tongke6** [comment]
@Repo-Zhuang 看起来是在 SCDB 容器里 resolve engine_bob 的 hostname 失败。

可以先 docker-compose ps 看下容器的状态，若 engine_bob 容器活着，那就是 docker 网络的问题。
如果是 docker 网络的问题，你可以尝试检索一下相关的解决方案。

**Comment by Repo-Zhuang** [comment]
已解决，感谢

**Comment by tongke6** [comment]
@Repo-Zhuang 是有遇到什么问题吗？

如果是在 mac 的 docker 容器里面运行 scdbclient，同样需要确保可以通过 host 参数指定的地址访问到 quickstart 里 docker-compose 绑定的端口。如果是在 mac 上（宿主机上）直接运行 scdbclient，命令是不需要做修改的。

**Comment by Repo-Zhuang** [comment]
问题已经解决了，但使用localhost无法访问。和window一样，替换成 host.docker.internal 后成功了

**Comment by TY-cc** [comment]
类似的，我也报了错误码三百，具体指令与报告如下：
```
[demo]alice> SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age <= 30 AND tb.is_active=1 GROUP BY ta.credit_rank;
[fetch]err: Code: 300, message:failed to askEngineInfoByTables: askEngineInfo failed to get engineInfo: failed to get engines: no auth
```
情况是这样的，我把scdbclient,scdbserver,scdbengine都编译成了可执行程序。看其报错提示，应该是scdbserver无法访问scdbengine，我仔细对照了toy_grm.json文件，用户证书与token都是无误的，这应该怎么排查？

**Comment by tongke6** [comment]
@TY-cc 看报错还是 token 的问题，方便贴一下 toy_grm.json 的配置文件，以及 scdbclient 侧的 users.json 文件内容吗？

**Comment by TY-cc** [comment]
scdbclient下的user.json内容如下：
```
{
  "alice": {
    "UserName": "alice",
    "Password": "some_password",
    "GrmToken": "__ALICE_TOKEN__"
  },
  "bob": {
    "UserName": "bob",
    "Password": "another_password",
    "GrmToken": "__BOB_TOKEN__"
  },
  "carol": {
    "UserName": "carol",
    "Password": "another_password",
    "GrmToken": "__CAROL_TOKEN__"
  },
  "root": {
    "UserName": "root",
    "Password": "root",
    "GrmToken": ""
  }
}
```

toy_grm.json内容如下：
```
{
  "engine": {
    "read_token": ["__ALICE_TOKEN__", "__BOB_TOKEN__"],
    "engines_info": [
      {
        "party": "alice",
        "url": ["localhost:8081"],
        "credential": ["__ALICE_CREDENTIAL__"]
      },
      { 
      "party": "bob", 
      "url": ["local:8082"], 
      "credential": ["__BOB_CREDENTIAL__"] 
      }
    ]
  },
  "table": {
    "read_token": ["__ALICE_TOKEN__", "__BOB_TOKEN__"],
    "ownerships": [
      { "tids": ["tid0"], "token": "__ALICE_TOKEN__" },
      { "tids": ["tid1"], "token": "__BOB_TOKEN__" }
    ],
    "table_schema": [
      {
        "tid": "tid0",
        "schema": {
          "ref_db_name": "alice",
          "ref_table_name": "user_credit",
          "columns": [
            { "column_name": "ID", "column_type": "string" },
            {
              "column_name": "credit_rank",
              "column_type": "long"
            },
            { "column_name": "income", "column_type": "long" },
            { "column_name": "age", "column_type": "long" }
          ]
        }
      },
      {
        "tid": "tid1",
        "schema": {
          "ref_db_name": "bob",
          "ref_table_name": "user_stats",
          "columns": [
            { "column_name": "ID", "column_type": "string" },
            {
              "column_name": "order_amount",
              "column_type": "float"
            },
            { "column_name": "is_active", "column_type": "long" }
          ]
        }
      }
    ]
  }
}
```

**Comment by TY-cc** [comment]
@tongke6 我没有依赖docker-compose.yml文件启动scdb与scdbengine，我猜测可能是sql没有启动有关

**Comment by taochen-ant** [comment]
> @tongke6 我没有依赖docker-compose.yml文件启动scdb与scdbengine，我猜测可能是sql没有启动有关

请问一下你是通过什么方式启动的scdb？

**Comment by TY-cc** [comment]
我直接在linux下将scdb编译成了可执行文件，然后通过添加toy_grm.json作为参数启动了scdb。

**Comment by taochen-ant** [comment]
能麻烦给一下scdb启动时的配置文件吗？配置文件中toy_grm_conf中的toy_grm.json 文件是否和之前你提供的一致

如果没有指定配置文件，系统会默认读取cmd/scdbserver/config.yml 这个配置。

**Comment by TY-cc** [comment]
scdb启动涉及了两个文件，分别是cmd/scdbserver/config.yml，还有toy_grm.json(该文件的内容在上面已经提供了，是一致的)。
```
config.yml文件内容如下：
scdb_host: http://localhost:8084
port: 8084
protocol: http
query_result_callback_timeout: 3m
session_expire_time: 3m
session_expire_check_time: 100ms
log_level: debug
storage:
  type: sqlite
  conn_str: scdb.db
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
grm:
  grm_mode: toygrm
  toy_grm_conf: toy_grm.json
  #toy_grm_conf: pkg/grm/toygrm/testdata/toy_grm.json
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  spu:
    protocol: SEMI2K
    field: FM64
    sigmoid_mode: SIGMOID_REAL
```

抱歉我的错误，忘了还有这个文件，所以端口启动错误(我访问的是8080端口，但实际应该8084)。换了端口访问后。直接提示如下错误
`[fetch]err: Code: 101, message:user root authentication failed`

**Comment by taochen-ant** [comment]
这个问题可能是你SCDB数据库里的root用户的密码和你user.json中的密码不一致导致的这个问题。SCDB在启动时，会尝试在数据库中创建root用户，我看你配置中conn_str使用的是sqlite，这种情况下，你可以采取下面两种方案：
一、将已有的scdb.db删除后，配置环境变量`export SCQL_ROOT_PASSWORD=root` ，随后重新启动SCDB。
二、你在启动SCDB的时候，SCDB在启动时候会将root的密码打印在控制台中，比如`generated root password: d-#]7921y4o08q,3 ,  please keep it safe`，你可以根据这个信息直接更改user.json中的root密码。

**Comment by TY-cc** [comment]
1：将scdb.db删除后，export SCQL_ROOT_PASSWORD=root，重新启动scdb依旧没有反应，。
2：我在启动scdb的时候，没有root的密码打印出来，启动时候控制台信息如下
```
2023-05-25 13:18:55.5251 INFO main.go:86 Starting to read config file: config.yml
2023-05-25 13:18:55.5251 INFO main.go:99 Starting to connect to database and do bootstrap if necessary...
2023-05-25 13:18:55.5251 INFO main.go:123 Starting to serve request with http...
```

**Comment by taochen-ant** [comment]
> 1：将scdb.db删除后，export SCQL_ROOT_PASSWORD=root，重新启动scdb后，在scdbclient依旧得到如下错误： `[fetch]err: Code: 101, message:user root authentication failed` 2：我在启动scdb的时候，没有root的密码打印出来，启动时候控制台信息如下
> 
> ```
> 2023-05-25 13:18:55.5251 INFO main.go:86 Starting to read config file: config.yml
> 2023-05-25 13:18:55.5251 INFO main.go:99 Starting to connect to database and do bootstrap if necessary...
> 2023-05-25 13:18:55.5251 INFO main.go:123 Starting to serve request with http...
> ```

对于问题一：
    麻烦能给一下你详细的操作命令吗？以及相关的config.yaml, user.json配置吗？ 另外麻烦也给一下scdbclient报错时，scdb的日志详情。
对于问题二：
    只有在没有设置环境变量切数据库中没有root用户的时候，才会由scdb自动创建root用户并打印密码至控制台。上述情况可能是数据库已经有了root用户，或者已经导入了环境变量导致的。

**Comment by TY-cc** [comment]
问题已经解决了。我在数据库重新创建了root用户，然后设置密码为root，删除掉scdb.db文件后，重新启动root用户就可以重新通过了。但是我在数据库创建alice账号后，在alice账户下也出现了这类错误。
操作指令：
1、进入scdbclient，指令`./scdbclient prompt --host=http://192.168.5.133:8084 --usersConfFileName=users.json --sync`
2、切换alice用户，指令`switch alice`
3、alice下显示数据库，指令`show databases;`
client返回错误：`[fetch]err: Code: 101, message:user alice authentication failed`

scdb的日志如下：
```
2023-05-25 15:58:23.5253 ERROR privileges.go:70 get user privilege record fail: user alice, host %
2023-05-25 15:58:23.5253 ERROR submit_and_get_handler.go:65 |RequestID:|SessionID:|ActionName:SCDBSubmitAndGetHandler@/public/submit_and_get|CostTime:763.309µs|Reason:InvalidRequest|ErrorMsg:user alice authentication failed|Request:user:{user:{account_system_type:NATIVE_USER native_user:{name:"alice"}}} query:"show databases"|ClientIP:192.168.5.133
2023-05-25 15:58:23.5253 INFO server.go:146 |GIN|status=200|method=POST|path=/public/submit_and_get|ip=192.168.5.133|latency=856.756µs|
```
user.json配置如下：
```
{
  "alice": {
    "UserName": "alice",
    "Password": "some_password",
    "GrmToken": "__ALICE_TOKEN__"
  },
  "bob": {
    "UserName": "bob",
    "Password": "another_password",
    "GrmToken": "__BOB_TOKEN__"
  },
  "carol": {
    "UserName": "carol",
    "Password": "another_password",
    "GrmToken": "__CORAL_TOKEN__"
  },
  "root": {
    "UserName": "root",
    "Password": "root",
    "GrmToken": ""
  }
}
```

config.yml文件配置如下：
```
scdb_host: http://localhost:8084
port: 8084
protocol: http
query_result_callback_timeout: 3m
session_expire_time: 3m
session_expire_check_time: 100ms
log_level: debug
storage:
  type: sqlite
  conn_str: scdb.db
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
grm:
  grm_mode: toygrm
  toy_grm_conf: toy_grm.json
  #toy_grm_conf: pkg/grm/toygrm/testdata/toy_grm.json
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  spu:
    protocol: SEMI2K
    field: FM64
    sigmoid_mode: SIGMOID_REAL
```

我猜测还是数据库账号的问题
