### ISSUE TITLE
scqlengine部署失败，msg=[Enforce fail at engine/auth/pkey.cc:43] fp. Failed to open file:

### ISSUE THREAD

**Issue by chansono** [secretflow/scql#157]
参照“https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/getting_started/deployment”进行scql部署。
- 版本：latest
- 问题：部署scqlengine（alice为例）时，engine容器启动失败。
- docker ps 查看：
![image](https://github.com/secretflow/scql/assets/14270233/074b6c90-885d-4058-a827-364497c63352)
- docker logs 日志：
![image](https://github.com/secretflow/scql/assets/14270233/3c85fe0b-09fc-423e-b690-b83cf838dd6e)
- 注：
    - latest与0.3.0b1版本相同报错；
    - 0.2.0b2可正常部署成功。

**Comment by jingshi-ant** [comment]
您好，0.3.0b1版本因为去除了GRM，因此需要依赖公私钥来验证身份。
deployment还没有做及时的更新，因此新版无法正确部署。
建议：我们的 快速开始 文档的流程已经根据新版更新过了，建议您在我们更新deployment文档前，过一下 快速开始 （预计15min）并参照 快速开始 文档 的流程，修改补充engine的配置，以完成scql的多机部署。

**Comment by chansono** [comment]
> 您好，0.3.0b1版本因为去除了GRM，因此需要依赖公私钥来验证身份。 deployment还没有做及时的更新，因此新版无法正确部署。 建议：我们的 快速开始 文档的流程已经根据新版更新过了，建议您在我们更新deployment文档前，过一下 快速开始 （预计15min）并参照 快速开始 文档 的流程，修改补充engine的配置，以完成scql的多机部署。

谢谢，已经成功部署了~~

**Comment by jingshi-ant** [comment]
@chansono 
赞~ 
另外如果您有兴趣，也非常欢迎您贡献更新 部署 文档，以帮助其它用户~

**Comment by chansono** [comment]
### SCQL（0.3.0b1）多机部署

**alice/bob的私钥生成与公钥交换**

```
cd scql
examples/docker-compose/setup.sh
```
**engine（alice为例）部署**

1、alice相关测试文件拷贝到alice节点
- 将“scql/examples/docker-compose/engine/alice”拷贝到alice节点，其中gflags.conf需要后续修改
- 将“scql/examples/docker-compose/mysql/initdb/alice_init.sql”拷贝到alice节点
- 将[部署文档](https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/getting_started/deployment)中alice的“docker-compose.yaml”拷贝到alcie节点，并后续修改
![捕获](https://github.com/secretflow/scql/assets/14270233/070c1b39-e0b1-4b20-a1b8-79a5baa25a27)

2、docker-compose.yaml 修改后如下
```
version: "3.8"
services:
  engine:
    cap_add:
      - NET_ADMIN
    command:
      - /home/admin/bin/scqlengine
      - --flagfile=/home/admin/engine/conf/gflags.conf
    restart: always
    image: secretflow/scql:latest
    ports:
      - 8080:8080
    volumes:
      - ./conf/gflags.conf:/home/admin/engine/conf/gflags.conf
      - ./conf/ed25519key.pem:/home/admin/engine/conf/ed25519key.pem
      - ./conf/authorized_profile.json:/home/admin/engine/conf/authorized_profile.json
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=testpass
      - TZ=Asia/Shanghai
    healthcheck:
      retries: 10
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - mysql
      timeout: 20s
    expose:
      - "3306"
    restart: always
    volumes:
      - ./alice_init.sql:/docker-entrypoint-initdb.d/alice_init.sql
```

3、gflags.conf 修改后如下
```
--listen_port=8080
--datasource_router=embed
--enable_scdb_authorization=true
--engine_credential=credential_alice
--server_enable_ssl=false
--scdb_enable_ssl_as_client=false
--peer_engine_enable_ssl_as_client=false
--embed_router_conf={"datasources":[{"id":"ds001","name":"mysql db","kind":"MYSQL","connection_str":"db=alice;user=root;password=testpass;host=mysql;auto-reconnect=true"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
# party authentication flags
--enable_self_auth=true
--enable_peer_auth=true
--private_key_pem_path=/home/admin/engine/conf/ed25519key.pem
--authorized_profile_path=/home/admin/engine/conf/authorized_profile.json
```

**scdb部署**

scdb相关文件拷贝到scdb节点
- 将“scql/examples/docker-compose/mysql/initdb/scdb_init.sql”拷贝到scdb节点
- 将[部署文档](https://www.secretflow.org.cn/docs/scql/latest/zh-Hans/getting_started/deployment)中sccdb的“docker-compose.yaml”与“config.yml”拷贝到scdb节点
![捕获1](https://github.com/secretflow/scql/assets/14270233/cadfdfc3-f5fa-4e14-b341-f1c6b265db77)
