### ISSUE TITLE
关于scql engin任务执行失败后，内存不释放问题

### ISSUE THREAD

**Issue by EtanWatson** [secretflow/scql#448]
有zongbu和beijing两个scql engine节点，其中zongbu表为10亿+数据，beijing表为3千万+数据

任务sql：
```
select  a.user_id_a,a.month_id, a.day_id,a.prov_id   from zbsjfwvfxe_dwd_d_prd_cb_relation_uu a join provbjfpjq_dwd_d_prd_cb_relation_uu b on a.user_id_a=b.user_id_a
```
{"xxlJobId":126,"resultMsg":"Error: code=320, msg=\"RunExecutionPlan run jobs(ef3ffa1d-e5f5-11ef-a4f5-0242ac160002) failed, catch std::exception=[external/yacl/yacl/link/transport/channel.cc:427] Get data timeout, key=ef3ffa1d-e5f5-11ef-a4f5-0242ac160002-0:821:ALLGATHER\""}
当时针对该问题修改了engine的配置参数link_recv_timeout_ms为半个小时
```
--link_recv_timeout_ms=1800000
```

执行下面sql时候：
```
select  a.user_id_a,a.month_id, a.day_id,a.prov_id   from zbsjfwvfxe_dwd_d_prd_cb_relation_uu a join provbjfpjq_dwd_d_prd_cb_relation_uu b on a.user_id_a=b.user_id_a  group by a.user_id_a,a.month_id,a.day_id,a.prov_id
```
报错内存溢出：{"xxlJobId":138,"resultMsg":"Error: code=320, msg=\"RunExecutionPlan run jobs(91e4b1b6-e689-11ef-a4f5-0242ac160002) failed, catch std::exception=[./engine/core/primitive_builder.h:74] Out of memory: malloc of size 274877906944 failed\""}
但是内存溢出后任务失败后
两个参与节点内存一直不回收（持续一天多，也没下来，并且这两个计算节点没有其他正在计算的任务）
beijing节点
![Image](https://github.com/user-attachments/assets/87a53b5e-45a7-455a-858a-dd90b1b2a83f)
zongbu节点
![Image](https://github.com/user-attachments/assets/3ecc07a2-121b-40c3-9aec-36de50a9c4af)

**Comment by Chrisdehe** [comment]
查看下进程，有没有相关的任务还在运行呢，kill掉后再看下呢

**Comment by tongke6** [comment]
@EtanWatson 请提供一下使用的版本和环境信息

**Comment by EtanWatson** [comment]
老师，我部署p2p模式，使用scql版本为0.9.2b1，在一台机器上部署了两个参与方，使用不同的端口，查询本方的数据是好使的，但是使用样例中的语句查询的时候，SELECT ta.credit_rank, COUNT(*) as cnt, AVG(ta.income) as avg_income, AVG(tb.order_amount) as avg_amount FROM ta INNER JOIN tb ON ta.ID = tb.ID WHERE ta.age >= 20 AND ta.age，报错
```
Error: run query: DoQuery response: {
"status": {
"code": 320,
"message": "RunExecutionPlan create session(412753ca-ed9e-11ef-85d2-0242ac150002) failed, catch std::exception=[Enforce fail at engine/services/engine_service_impl.cc:215] peer_whole_graph_checksum == whole_graph_checksum. peer_whole_graph_checksum: c1a3f322d8f4276a6ad6a1121eb6c64f2df4f9dfc376a422902d58732344cd01c369a4da01e4285f71633308c0c692819b84132ed11f9cba28c4a1637a412f44 != whole_graph_checksum: e54db4789b9f6077a14c1ba61379722909e0b47408cbc023fb3e3593063cec51
Stacktrace:
#0 scql::engine::EngineServiceImpl::RunExecutionPlan()+0x55cb14d75858
#1 brpc::policy::ProcessHttpRequest()+0x55cb187040b2
#2 brpc::ProcessInputMessage()+0x55cb186aa88b
#3 brpc::InputMessenger::OnNewMessages()+0x55cb186aca64
#4 brpc::Socket::ProcessEvent()+0x55cb187b2ed5
#5 bthread::TaskGroup::task_runner()+0x55cb1881b2af
#6 bthread_make_fcontext+0x55cb18803a51
"
}
}
```
我的配置如下config.yml
zongbu参与方
```
intra_server:
  host: 0.0.0.0
  port: 8080
inter_server:
  port: 8081
log_level: debug
party_code: zongbu
session_expire_time: 24h
session_expire_check_time: 1m
party_info_file: "/home/admin/configs/party_info.json"
private_key_path: "/home/admin/configs/ed25519key-zongbu.pem"
intra_host: http://xx.xxx.85.158:50050
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  uris:
    - for_peer: xx.xxx.85.158:48086
      for_self: xx.xxx.85.158:58083
storage:
  type: mysql
  conn_str: "user:password@tcp(mysqlip:port)/borkerzongbu?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
```
prov参与方：
```
intra_server:
  host: 0.0.0.0
  port: 8080
inter_server:
  port: 8081
log_level: debug
party_code: prov
session_expire_time: 24h
session_expire_check_time: 1m
party_info_file: "/home/admin/configs/party_info.json"
private_key_path: "/home/admin/configs/ed25519key-prov.pem"
intra_host: http://xx.xxx.xx.158:50051
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  uris:
    - for_peer: xx.xxx.85.158:48085
      for_self: xx.xxx.85.158:58084
storage:
  type: mysql
  conn_str: "user:password@tcp(mysqlip:port)/prov?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
```
gflags.conf
zongbu参与方
```
--listen_port=8003
--link_port=8004
--enable_separate_link_port=true
--datasource_router=embed
--enable_driver_authorization=false
--server_enable_ssl=false
--driver_enable_ssl_as_client=false
--peer_engine_enable_ssl_as_client=false
--embed_router_conf={"datasources":[{"id":"ds001","name":"mysql db","kind":"MYSQL","connection_str":"db=zongbu;user;password;host=xx.xxx.85.156;port=xxxx;auto-reconnect=true"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
# party authentication flags
--enable_self_auth=false
--enable_peer_auth=false
```
prov参与方
```
--listen_port=8003
--link_port=8004
--enable_separate_link_port=true
--datasource_router=embed
--enable_driver_authorization=false
--server_enable_ssl=false
--driver_enable_ssl_as_client=false
--peer_engine_enable_ssl_as_client=false
--embed_router_conf={"datasources":[{"id":"ds001","name":"mysql db","kind":"MYSQL","connection_str":"db=prov;user;password;host=xx.xxx.85.156;port=xxxx;auto-reconnect=true"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
# party authentication flags
--enable_self_auth=false
--enable_peer_auth=false
```

> 建议docker restart来手动释放内存。 从报错看，需要malloc 200G+的内存，有点夸张，交集的size可能过大了，建议先评估下结果大小看下是否加内存（减少数据，或者使用p2p模式下的streaming模式来降低内存用量），不然任务没法run完
