### ISSUE TITLE
【文档季】【SCQL】验证文档「P2P 模式部署」，包括验证文档流程以及示例代码的正确性

### ISSUE THREAD

**Issue by baikeqichenwei** [secretflow/scql#485]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）Phase 4 ](https://studio.secretflow.com/activity/fy3n4tddfe3xteq/detail)任务 ISSUE，欢迎社区开发者参与共建～
> - 认领前，辛苦确认是否完成[报名](https://studio.secretflow.com/activity/fy3n4tddfe3xteq/detail)～
> - 更多任务，可查看 [「OSCP Phase4 Season of Docs」Project](https://github.com/orgs/secretflow/projects/12)
>
> This ISSUE is one of the tasks of the  [SecretFlow Open Source Contribution Plan (referred to as SF OSCP) Phase 4](https://studio.secretflow.com/activity/fy3n4tddfe3xteq/detail) . Welcome to join us in building it together!
> - Before claiming a task, please make sure you have [signed up](https://studio.secretflow.com/activity/fy3n4tddfe3xteq/detail).
> - For more tasks, you can check the ["OSCP Phase4 Season of Docs" Project](https://github.com/orgs/secretflow/projects/12).

### 任务介绍
+ 任务名称：验证文档 [P2P 模式部署](https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.2b1/topics/deployment/how-to-deploy-p2p-cluster) ，包括验证文档流程以及示例代码的正确性
+ 技术方向：scql/docs
+ 任务难度：初级🌟

### 详细要求
请基于 https://www.secretflow.org.cn/zh-CN/docs/scql/0.9.3b1/topics/deployment/how-to-deploy-p2p-cluster 进行验证，确认文档描述是否正确、是否和对应版本代码一致。示例代码能够正确执行、结果是否符合预期，并对文档内容通顺（语句与错别字）与易理解性进行修正。

+ 操作指引：
    - 若代码正确、文档无误，则在本 ISSUE 下回复【任务序号 + 验证成功 + 代码成功验证截图证明】
    - 若代码或文档内容需修改，则在scql中提交相应的 PR（需关联本ISSUE），同时更新中英文版本，参考[操作流程](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version)
+ 代码规范：参照scql的要求
+ 范例与参考材料：
    - [https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version)
    - [https://github.com/secretflow/secretflow/pull/445](https://github.com/secretflow/secretflow/pull/445)
    - [https://github.com/secretflow/secretflow/pull/561](https://github.com/secretflow/secretflow/pull/561)

### 能力要求
    - 了解基本 git 操作
    - 对scql有一定了解，成功运行过部分示例

**Comment by HoKinChung** [comment]
HoKinChung Give it to me

**Comment by baikeqichenwei** [comment]
👋 @HoKinChung just a quick reminder to make your contributions within 7 days, otherwise, the issue will be reassigned and the assignee of this issue will be released to other people. Let us know if you have any questions!😄
hello @HoKinChung 恭喜成功认领该任务，温馨提示，请在 7 天内做出您的贡献，超出 7 天任务将会被释放哦～如果你有任何疑问，请告知我们！😄

**Comment by HoKinChung** [comment]
485 验证成功

# 部署 Alice 环境
## 创建工作区
<img width="145" alt="Image" src="https://github.com/user-attachments/assets/8116566c-528e-4d1e-8656-4c3f9545a72f" />

## 准备状态数据、源数据
<img width="1195" alt="Image" src="https://github.com/user-attachments/assets/7c815203-b9b8-4a0e-9db3-a98586e0eb2f" />

## 配置 SCQLBroker
<img width="845" alt="Image" src="https://github.com/user-attachments/assets/e9a06fe4-97e9-4790-b390-21944963eea9" />

`config.yml` where `__ENGINE_URL__` is `engine_alice:8004`, `__MYSQL_ROOT_PASSWORD__` is `secretflow_alice`

```yaml
intra_server:
  host: 0.0.0.0
  port: 8080
inter_server:
  port: 8081
log_level: debug
party_code: alice
session_expire_time: 24h
session_expire_check_time: 1m
party_info_file: "/home/admin/configs/party_info.json"
private_key_path: "/home/admin/configs/ed25519key.pem"
intra_host: broker_alice:8080
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  uris:
    - for_peer: engine_alice:8004
      for_self: engine_alice:8003
storage:
  type: mysql
  conn_str: "root:secretflow_alice@tcp(mysql_alice:3306)/brokeralice?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
```

## 配置 SCQLEngine
<img width="537" alt="Image" src="https://github.com/user-attachments/assets/23d84381-a177-4fd7-8fee-66d0fdf38e7e" />

`gflags.conf` where `__MYSQL_ROOT_PASSWORD__` is `secretflow_alice`

## 创建 docker-compose 文件
`docker-compose.yaml` where `__INTRA_PORT__`,` __INTER_PORT__` and ` __ENGINE_PORT__` are `8080`, `8081` and `8003` respectively, `__MYSQL_ROOT_PASSWORD__ ` is `secretflow_alice`

```yaml
version: '3.8'
services:
  broker_alice:
    image: secretflow/scql:latest
    command:
      - /home/admin/bin/broker
      - -config=/home/admin/configs/config.yml
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./config.yml:/home/admin/configs/config.yml
      - ./party_info.json:/home/admin/configs/party_info.json
      - ./ed25519key.pem:/home/admin/configs/ed25519key.pem
  engine_alice:
    cap_add:
      - NET_ADMIN
    command:
      - /home/admin/bin/scqlengine
      - --flagfile=/home/admin/engine/conf/gflags.conf
    image: secretflow/scql:latest
    ports:
      - 8003:8003
    volumes:
      - ./gflags.conf:/home/admin/engine/conf/gflags.conf
  mysql_alice:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secretflow_alice
      - TZ=Asia/Shanghai
    healthcheck:
      retries: 10
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - mysql
      timeout: 20s
    expose:
      - "3306"
    restart: always
    volumes:
      - ./alice_init.sql:/docker-entrypoint-initdb.d/alice_init.sql
      - ./broker_init_alice.sql:/docker-entrypoint-initdb.d/broker_init_alice.sql
```

## 准备身份验证文件
<img width="857" alt="Image" src="https://github.com/user-attachments/assets/c93573c3-7451-4eff-8300-527ecab0b386" />

`party_info.json` file

```json
{
    "participants": [
      {
        "party_code": "alice",
        "endpoint": "https://broker_alice:8081",
        "pubkey": "MCowBQYDK2VwAyEAoRrC3Q2aC1aa+54QoS+Ll2KlGDVHQLu5nNiPwjiSdnA="
      },
      {
        "party_code": "bob",
        "endpoint": "https://broker_bob:9081",
        "pubkey": "MCowBQYDK2VwAyEA8mFE47NDLy921Hno6heNRoOH2Gn3nyd1/vJzf9+/+34="
      }
    ]
}
```

## 启动服务

`docker compose -f docker-compose.yaml up -d`
<img width="1203" alt="Image" src="https://github.com/user-attachments/assets/5ae7de78-be0b-44a7-b2ff-9f8ebc780492" />

`docker logs -f alice-engine_alice-1`
<img width="1212" alt="Image" src="https://github.com/user-attachments/assets/5f709a46-f5d4-4749-a0d0-d3579f84863c" />

`docker logs -f alice-engine_alice-1`
<img width="1208" alt="Image" src="https://github.com/user-attachments/assets/5b07a5f8-7058-4277-95c0-4577b067a8e9" />

**Comment by HoKinChung** [comment]
# 步骤二：部署 Bob 环境

## 准备状态数据、源数据

<img width="1195" alt="Image" src="https://github.com/user-attachments/assets/5c0a5a95-eff5-4e5f-b7d8-5cdc0b48d62d" />
 
## 配置 SCQLBroker

`config.yml`

```yaml
intra_server:
  host: 0.0.0.0
  port: 8080
inter_server:
  port: 8081
log_level: debug
party_code: bob
session_expire_time: 24h
session_expire_check_time: 1m
party_info_file: "/home/admin/configs/party_info.json"
private_key_path: "/home/admin/configs/ed25519key.pem"
intra_host: broker_bob:8080
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  uris:
    - for_peer: engine_bob:8004
      for_self: engine_bob:8003
storage:
  type: mysql
  conn_str: "root:secretflow_bob@tcp(mysql_bob:3306)/brokerbob?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
```


## 配置 SCQLEngine

`gflags.conf`

```
--listen_port=8003
--datasource_router=embed
--enable_driver_authorization=false
--server_enable_ssl=false
--driver_enable_ssl_as_client=false
--peer_engine_enable_ssl_as_client=false
--embed_router_conf={"datasources":[{"id":"ds001","name":"mysql db","kind":"MYSQL","connection_str":"db=bob;user=root;password=secretflow_bob;host=mysql_bob;auto-reconnect=true"}],"rules":[{"db":"*","table":"*","datasource_id":"ds001"}]}
# party authentication flags
--enable_self_auth=false
--enable_peer_auth=false
```

## 创建 docker-compose 文件

`docker-compose.yaml`
```yaml
version: '3.8'
services:
  broker_bob:
    image: secretflow/scql:latest
    command:
      - /home/admin/bin/broker
      - -config=/home/admin/configs/config.yml
    restart: always
    ports:
      - 9080:8080
      - 9081:8081
    volumes:
      - ./config.yml:/home/admin/configs/config.yml
      - ./party_info.json:/home/admin/configs/party_info.json
      - ./ed25519key.pem:/home/admin/configs/ed25519key.pem
  engine_bob:
    cap_add:
      - NET_ADMIN
    command:
      - /home/admin/bin/scqlengine
      - --flagfile=/home/admin/engine/conf/gflags.conf
    image: secretflow/scql:latest
    ports:
      - 9003:8003
    volumes:
      - ./gflags.conf:/home/admin/engine/conf/gflags.conf
  mysql_bob:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secretflow_bob
      - TZ=Asia/Shanghai
    healthcheck:
      retries: 10
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - mysql
      timeout: 20s
    expose:
      - "3306"
    restart: always
    volumes:
      - ./bob_init.sql:/docker-entrypoint-initdb.d/bob_init.sql
      - ./broker_init_bob.sql:/docker-entrypoint-initdb.d/broker_init_bob.sql
```

## 准备身份验证文件

`party_info.json`

```json
{
    "participants": [
      {
        "party_code": "alice",
        "endpoint": "https://broker_alice:8081",
        "pubkey": "MCowBQYDK2VwAyEAoRrC3Q2aC1aa+54QoS+Ll2KlGDVHQLu5nNiPwjiSdnA="
      },
      {
        "party_code": "bob",
        "endpoint": "https://broker_bob:9081",
        "pubkey": "MCowBQYDK2VwAyEA8mFE47NDLy921Hno6heNRoOH2Gn3nyd1/vJzf9+/+34="
      }
    ]
  }
```

## 启动服务

<img width="183" alt="Image" src="https://github.com/user-attachments/assets/ca477db0-f4ac-4638-aec8-3bc88b2d142a" />

`docker compose -f docker-compose.yaml up -d`

<img width="1199" alt="Image" src="https://github.com/user-attachments/assets/8dc585f3-1ed7-4125-99fe-48c4b3d79274" />

`docker logs -f bob-engine_bob-1`

<img width="1200" alt="Image" src="https://github.com/user-attachments/assets/273df120-45d5-464a-87c8-3ec00bd89117" />

`docker logs -f bob-broker_bob-1`

<img width="862" alt="Image" src="https://github.com/user-attachments/assets/742b5461-d093-4a78-965c-c2bdbdfe639e" />
